name: FlarumReader
main: org.sotap.FlarumReader.Main
version: "1.0.0"
author: sotapmc
api-version: "1.16"
api: []

commands:
  flarumreader:
    aliases: ["g"]
    description: The flarum forum reader in Minecraft world.
    permission: flarumreader.command
    permission-message: "You do not have the permission to use the command."
    usage: The command is invalid or you don't have the permission to use it.
permissions:
  flarumreader.login:
    default: true
  flarumreader.logout:
    default: true
  flarumreader.view:
    default: true
  flarumreader.reply:
    default: true
  flarumreader.list:
    default: true
  flarumreader.reload:
    default: op

